# Terraform Provider release workflow.
name: deploy to production

on:
  push:
    tags:
    - 'prod-*'
jobs:
  terraform-plan:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform/production'